catalogMode: prefer
cleanupUnusedCatalogs: true
ignoreWorkspaceRootCheck: true
saveExact: true
shellEmulator: true

packages:
  - src/*
  - fixtures/*

catalogs:
  cli:
    "@antfu/ni": 28.2.0
    "@isentinel/eslint-config": 4.9.0
    "@roblox-ts/luau-ast": 2.0.1
    "@typescript-eslint/eslint-plugin": 8.56.0
    "@typescript-eslint/parser": 8.56.0
    "@typescript-eslint/type-utils": 8.56.0
    "@typescript-eslint/utils": 8.56.0
    bumpp: 10.4.1
    eslint: 9.39.1
    eslint-plugin-n: 17.24.0
    eslint-plugin-pnpm: 1.5.0
    jiti: 2.6.1
    lint-staged: 16.2.7
    simple-git-hooks: 2.13.1
    ts-api-utils: 2.4.0
    tsdown: 0.20.3
    tsx: 4.21.0
  testing:
    "@antfu/utils": 9.3.0
    eslint-8: npm:eslint@^8.57.0
    eslint-plugin-eslint-plugin: 7.3.1
    eslint-vitest-rule-tester: 3.1.0
    publint: 0.3.17
    unplugin-unused: 0.5.7
    vitest: 4.0.18
  tsc:
    "@isentinel/tsconfig": 1.2.0
    typescript: 5.9.3
  types:
    "@rbxts/compiler-types": 3.0.0-types.0
    "@rbxts/types": 1.0.908
    "@types/node": 24.10.1
  utils:
    eslint-doc-generator: 3.1.0

configDependencies:
  "@pnpm/trusted-deps": 0.1.1+sha512-jI3PWNv2zCg9+KHI3qQTsa534c5nisZQrHFeWSyyHoUXcuzvjkXxQKPFLJ/qtNAF+PtKHDlRntO2aZKb3VDuHQ==

onlyBuiltDependencies:
  - unrs-resolver

onlyBuiltDependenciesFile: node_modules/.pnpm-config/@pnpm/trusted-deps/allow.json
