packages:
  - src/*
  - fixtures/*

catalogs:
  cli:
    '@antfu/ni': 25.0.0
    '@isentinel/eslint-config': 1.3.0
    '@typescript-eslint/eslint-plugin': 8.44.0
    '@typescript-eslint/parser': 8.44.0
    '@typescript-eslint/type-utils': 8.44.0
    '@typescript-eslint/utils': 8.44.0
    bumpp: 10.2.0
    eslint: 9.31.0
    eslint-plugin-pnpm: 1.0.0
    jiti: 2.4.2
    lint-staged: 16.1.2
    simple-git-hooks: 2.13.0
    ts-api-utils: 2.1.0
    tsdown: 0.12.9
    tsx: 4.20.3
    typescript: 5.8.3
  testing:
    eslint-8: npm:eslint@^8.57.0
    eslint-plugin-eslint-plugin: 6.5.0
    eslint-vitest-rule-tester: 2.2.0
    publint: 0.3.12
    unplugin-unused: 0.5.1
    vitest: 3.2.4
  types:
    '@rbxts/compiler-types': 3.0.0-types.0
    '@rbxts/types': 1.0.861
    '@types/node': 24.0.13
  utils:
    eslint-doc-generator: 2.2.2

configDependencies:
  '@pnpm/trusted-deps': 0.1.1+sha512-jI3PWNv2zCg9+KHI3qQTsa534c5nisZQrHFeWSyyHoUXcuzvjkXxQKPFLJ/qtNAF+PtKHDlRntO2aZKb3VDuHQ==

onlyBuiltDependencies:
  - unrs-resolver

onlyBuiltDependenciesFile: node_modules/.pnpm-config/@pnpm/trusted-deps/allow.json
