packages:
  - src/*
  - fixtures/*

catalogs:
  cli:
    "@antfu/ni": 26.1.0
    "@isentinel/eslint-config": 4.2.2
    "@roblox-ts/luau-ast": 2.0.1
    "@typescript-eslint/eslint-plugin": 8.46.4
    "@typescript-eslint/parser": 8.46.4
    "@typescript-eslint/type-utils": 8.46.4
    "@typescript-eslint/utils": 8.46.4
    bumpp: 10.2.3
    eslint: 9.39.1
    eslint-plugin-n: 17.23.1
    eslint-plugin-pnpm: 1.3.0
    jiti: 2.6.1
    lint-staged: 16.2.3
    simple-git-hooks: 2.13.1
    ts-api-utils: 2.1.0
    tsdown: 0.16.4
    tsx: 4.20.6
    typescript: 5.8.3
  testing:
    "@antfu/utils": 9.3.0
    eslint-8: npm:eslint@^8.57.0
    eslint-plugin-eslint-plugin: 7.2.0
    eslint-vitest-rule-tester: 3.0.0
    publint: 0.3.13
    unplugin-unused: 0.5.3
    vitest: 3.2.4
  types:
    "@rbxts/compiler-types": 3.0.0-types.0
    "@rbxts/types": 1.0.884
    "@types/node": 24.6.1
  utils:
    eslint-doc-generator: 2.3.0

configDependencies:
  "@pnpm/trusted-deps": 0.1.1+sha512-jI3PWNv2zCg9+KHI3qQTsa534c5nisZQrHFeWSyyHoUXcuzvjkXxQKPFLJ/qtNAF+PtKHDlRntO2aZKb3VDuHQ==

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - unrs-resolver

onlyBuiltDependenciesFile: node_modules/.pnpm-config/@pnpm/trusted-deps/allow.json

saveExact: true

shellEmulator: true
